version: '3.8'

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    expose:
      - 9090
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    networks:
      - prom-compose
      - promnet

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - "${GF_SERVER_HTTP_PORT}:3000"
    volumes:
      - ./grafana/config/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_PROTOCOL=${GF_SERVER_PROTOCOL}
      - GF_SERVER_HTTP_PORT=${GF_SERVER_HTTP_PORT}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_UNIFIED_ALERTING_ENABLED=${GF_UNIFIED_ALERTING_ENABLED}
      - GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE=${GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE}
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - TZ=${TIMEZONE}
      - GF_ALERTING_TELEGRAM_BOT_TOKEN=${GF_ALERTING_TELEGRAM_BOT_TOKEN}
      - GF_ALERTING_TELEGRAM_CHAT_ID=${GF_ALERTING_TELEGRAM_CHAT_ID}
    depends_on:
      - prometheus
      - renderer
    restart: unless-stopped
    networks:
      - prom-compose

  renderer:
      image: grafana/grafana-image-renderer:${GRAFANA_RENDERER_VERSION}
      environment:
        - TZ=${TIMEZONE}
      volumes:
        - ./grafana/config/renderer/config.json:/usr/src/app/config.json
      networks:
        - prom-compose
      expose:
        - 8081

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    container_name: node-exporter
    expose:
      - 9100
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - prom-compose

volumes:
  prometheus_data:
  grafana_data:

networks:
  prom-compose:
    driver: bridge
  promnet:
    name: promnet
    external: true
